### ISSUE TITLE
Incompatible with python docker 3.0.1

### ISSUE THREAD

**Issue by xkszltl** [goldmann/docker-squash#159]
`pip show docker` shows Version 3.0.1
Was working with 3.0.0

Similar issues were also found in other projects recently, e.g. https://github.com/ansible/awx/issues/1197

Here's the crash log:
```
2018-02-12 13:34:19,505 root         DEBUG    Running version 1.0.6
2018-02-12 13:34:19,506 root         DEBUG    Preparing Docker client...
2018-02-12 13:34:19,507 docker.utils.config DEBUG    Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2018-02-12 13:34:19,507 docker.utils.config DEBUG    Found file at path: /root/.docker/config.json
2018-02-12 13:34:19,507 root         ERROR    load_config() got an unexpected keyword argument 'config_dict'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/docker_squash/cli.py", line 86, in run
    from_layer=args.from_layer, tag=args.tag, output_path=args.output_path, tmp_dir=args.tmp_dir, development=args.development, cleanup=args.cleanup).run()
  File "/usr/lib/python2.7/site-packages/docker_squash/squash.py", line 30, in __init__
    self.docker = common.docker_client(self.log)
  File "/usr/lib/python2.7/site-packages/docker_squash/lib/common.py", line 46, in docker_client
    client = APIClientClass(**params)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 110, in __init__
    config_dict=self._general_configs
TypeError: load_config() got an unexpected keyword argument 'config_dict'
2018-02-12 13:34:19,515 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!
```

**Comment by goldmann** [comment]
The squash tool is not compatible with version 3.x of the Docker Python library, see #158. Please downgrade to 2.x until #158 is fixed.

I'm closing this because this looks like a duplicate. We can reopen it once #158 is fixed and above issue will still exist.

**Comment by lvlts** [comment]
Hi,

Also encountered same problem, the system is running *CentOS 7.5.1804 (Core)*, with the default python distribution (2.7.5):

```
2018-11-05 05:15:59,225 root         DEBUG    Running version 1.0.7
2018-11-05 05:15:59,225 root         DEBUG    Preparing Docker client...
2018-11-05 05:15:59,226 docker.utils.config DEBUG    Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2018-11-05 05:15:59,226 docker.utils.config DEBUG    Found file at path: /root/.docker/config.json
2018-11-05 05:15:59,226 root         ERROR    load_config() got an unexpected keyword argument 'config_dict'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/docker_squash/cli.py", line 87, in run
    from_layer=args.from_layer, tag=args.tag, output_path=args.output_path, tmp_dir=args.tmp_dir, development=args.development, cleanup=args.cleanup).run()
  File "/usr/lib/python2.7/site-packages/docker_squash/squash.py", line 30, in __init__
    self.docker = common.docker_client(self.log)
  File "/usr/lib/python2.7/site-packages/docker_squash/lib/common.py", line 46, in docker_client
    client = APIClientClass(**params)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 113, in __init__
    config_dict=self._general_configs
TypeError: load_config() got an unexpected keyword argument 'config_dict'
2018-11-05 05:15:59,227 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!
```

`python --version`:
```
Python 2.7.5
```

`pip show docker`:
```
---
Metadata-Version: 2.0
Name: docker
Version: 3.5.1
Summary: A Python library for the Docker Engine API.
Home-page: https://github.com/docker/docker-py
Author: None
Author-email: None
Installer: pip
License: Apache License 2.0
Location: /usr/lib/python2.7/site-packages
Requires: websocket-client, docker-pycreds, backports.ssl-match-hostname, ipaddress, six, requests
Classifiers:
  Development Status :: 5 - Production/Stable
  Environment :: Other Environment
  Intended Audience :: Developers
  Operating System :: OS Independent
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: 3.6
  Programming Language :: Python :: 3.7
  Topic :: Utilities
  License :: OSI Approved :: Apache Software License
```

`pip show docker-squash`:
```
---
Metadata-Version: 1.1
Name: docker-squash
Version: 1.0.7
Summary: Docker layer squashing tool
Home-page: https://github.com/goldmann/docker-squash
Author: Marek Goldmann
Author-email: marek.goldmann@gmail.com
License: MIT
Location: /usr/lib/python2.7/site-packages
Requires: docker, six
Classifiers:
Entry-points:
  [console_scripts]
  docker-squash = docker_squash.cli:run
```
